### PR TITLE
pekko 287: Add pekko-cluster-docker-compose-java sample

### PR DESCRIPTION
**Pull request by sam-byng**
From https://github.com/apache/incubator-pekko/issues/287

java: git commit ref: 6501f62e6c79140fd623c167f90eb464bee66ec6
scala: git commit ref: 395a9a1f4fec7da39d1b0b66bc6f7f0f65180bff

### CODE REVIEW

**Comment by pjfanning** [comment]
@sam-byng is the idea to add these unmodified to this repo? I think this makes sense because when we modify them to be pekko-based, we will have the full history of the changes.

**Comment by pjfanning** [comment]
PS it seems like these fail the build because the scalafmt isn't right but that's ok - we can merge this and then fix the format, etc.

**Comment by sam-byng** [comment]
I've converted files over to docker and updated java image to 11 / sbt image to 1.8.2. However now seeing issue with the pekko actor scheduler:

We see
`Exception in thread "main" java.lang.IllegalStateException: cannot enqueue after timer shutdown`

and then 

`Exception in thread "main" java.lang.IllegalStateException: cannot create children while terminating or terminated`

I'm unsure whether this is caused by some config on the test code side (in this PR) or in the internal org.apache.pekko.actorResolver code.

other examples of the issue are @ : 
- https://discuss.lightbend.com/t/gracefulstop-in-cluster-mode-cannot-enqueue-after-timer-shutdown/729
- https://stackoverflow.com/questions/31229622/scala-play-framework-getting-cannot-enqueue-after-timer-shutdown-error-when

```
+ for i in {1..10}
+ echo 'Checking for MemberUp logging...'
Checking for MemberUp logging...
+ docker logs pekko-sample-cluster-docker-compose-java_seed_1
+ grep 'Member is Up'
+ wc -l
SLF4J: A number (4) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
Exception in thread "main" java.lang.IllegalStateException: cannot enqueue after timer shutdown
        at org.apache.pekko.actor.LightArrayRevolverScheduler.scheduleOnce(LightArrayRevolverScheduler.scala:165)
        at org.apache.pekko.actor.Scheduler$$anon$1.<init>(Scheduler.scala:88)
        at org.apache.pekko.actor.Scheduler.scheduleWithFixedDelay(Scheduler.scala:85)
        at org.apache.pekko.actor.Scheduler.scheduleWithFixedDelay$(Scheduler.scala:83)
        at org.apache.pekko.actor.LightArrayRevolverScheduler.scheduleWithFixedDelay(LightArrayRevolverScheduler.scala:109)
        at org.apache.pekko.cluster.ddata.protobuf.ReplicatorMessageSerializer.<init>(ReplicatorMessageSerializer.scala:175)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.apache.pekko.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:50)
        at scala.util.Try$.apply(Try.scala:210)
        at org.apache.pekko.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:45)
        at org.apache.pekko.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$5(ReflectiveDynamicAccess.scala:58)
        at scala.util.Success.flatMap(Try.scala:258)
        at org.apache.pekko.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:57)
        at org.apache.pekko.serialization.Serialization.serializerOf(Serialization.scala:403)
        at org.apache.pekko.serialization.Serialization.$anonfun$serializers$2(Serialization.scala:437)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
        at scala.collection.immutable.HashMapBuilder.addAll(HashMap.scala:2360)
        at scala.collection.immutable.HashMap$.from(HashMap.scala:2182)
        at scala.collection.immutable.HashMap$.from(HashMap.scala:2158)
        at scala.collection.MapOps$WithFilter.map(Map.scala:381)
        at org.apache.pekko.serialization.Serialization.<init>(Serialization.scala:437)
        at org.apache.pekko.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:28)
        at org.apache.pekko.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:24)
        at org.apache.pekko.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1177)
        at org.apache.pekko.actor.ActorSystemImpl.$anonfun$loadExtensions$1(ActorSystem.scala:1220)
        at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
        at org.apache.pekko.actor.ActorSystemImpl.loadExtensions$1(ActorSystem.scala:1214)
        at org.apache.pekko.actor.ActorSystemImpl.loadExtensions(ActorSystem.scala:1233)
        at org.apache.pekko.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1054)
        at org.apache.pekko.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1041)
        at org.apache.pekko.actor.ActorSystemImpl._start(ActorSystem.scala:1040)
        at org.apache.pekko.actor.ActorSystemImpl.start(ActorSystem.scala:1064)
        at org.apache.pekko.actor.typed.ActorSystem$.createInternal(ActorSystem.scala:300)
        at org.apache.pekko.actor.typed.ActorSystem$.apply(ActorSystem.scala:208)
        at org.apache.pekko.actor.typed.ActorSystem$.create(ActorSystem.scala:245)
        at org.apache.pekko.actor.typed.ActorSystem.create(ActorSystem.scala)
        at com.example.ClusteringApp.main(ClusteringApp.java:13)
Caused by: org.apache.pekko.actor.SchedulerException: cannot enqueue after timer shutdown
SLF4J: A number (4) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
Exception in thread "main" java.lang.IllegalStateException: cannot create children while terminating or terminated
        at org.apache.pekko.actor.dungeon.Children.makeChild(Children.scala:306)
        at org.apache.pekko.actor.dungeon.Children.attachChild(Children.scala:62)
        at org.apache.pekko.actor.dungeon.Children.attachChild$(Children.scala:61)
        at org.apache.pekko.actor.ActorCell.attachChild(ActorCell.scala:420)
        at org.apache.pekko.actor.ActorSystemImpl.systemActorOf(ActorSystem.scala:906)
        at org.apache.pekko.actor.typed.scaladsl.adapter.package$TypedActorSystemOps$.internalSystemActorOf$extension(package.scala:96)
        at org.apache.pekko.actor.typed.internal.receptionist.ReceptionistImpl.<init>(ReceptionistImpl.scala:49)
        at org.apache.pekko.actor.typed.receptionist.Receptionist$.createExtension(Receptionist.scala:107)
        at org.apache.pekko.actor.typed.receptionist.Receptionist$.createExtension(Receptionist.scala:106)
        at org.apache.pekko.actor.typed.internal.ExtensionsImpl.$anonfun$createExtensionInstance$1(ExtensionsImpl.scala:102)
        at scala.Option.getOrElse(Option.scala:201)
        at org.apache.pekko.actor.typed.internal.ExtensionsImpl.createExtensionInstance(ExtensionsImpl.scala:102)
        at org.apache.pekko.actor.typed.internal.ExtensionsImpl.registerExtension(ExtensionsImpl.scala:88)
        at org.apache.pekko.actor.typed.internal.ExtensionsImpl.registerExtension$(ExtensionsImpl.scala:86)
        at org.apache.pekko.actor.typed.internal.adapter.ActorSystemAdapter.registerExtension(ActorSystemAdapter.scala:54)
        at org.apache.pekko.actor.typed.internal.ExtensionsImpl.$anonfun$loadExtensions$1(ExtensionsImpl.scala:54)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at org.apache.pekko.actor.typed.internal.ExtensionsImpl.loadExtensions$1(ExtensionsImpl.scala:47)
        at org.apache.pekko.actor.typed.internal.ExtensionsImpl.loadExtensions(ExtensionsImpl.scala:75)
        at org.apache.pekko.actor.typed.internal.ExtensionsImpl.loadExtensions$(ExtensionsImpl.scala:40)
        at org.apache.pekko.actor.typed.internal.adapter.ActorSystemAdapter.loadExtensions(ActorSystemAdapter.scala:54)
        at org.apache.pekko.actor.typed.internal.adapter.ActorSystemAdapter$LoadTypedExtensions.<init>(ActorSystemAdapter.scala:164)
        at org.apache.pekko.actor.typed.internal.adapter.ActorSystemAdapter$LoadTypedExtensions$.createExtension(ActorSystemAdapter.scala:170)
        at org.apache.pekko.actor.typed.internal.adapter.ActorSystemAdapter$LoadTypedExtensions$.createExtension(ActorSystemAdapter.scala:167)
        at org.apache.pekko.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1177)
        at org.apache.pekko.actor.ActorSystemImpl.$anonfun$loadExtensions$1(ActorSystem.scala:1220)
        at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
        at org.apache.pekko.actor.ActorSystemImpl.loadExtensions$1(ActorSystem.scala:1214)
        at org.apache.pekko.actor.ActorSystemImpl.loadExtensions(ActorSystem.scala:1233)
        at org.apache.pekko.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1054)
        at org.apache.pekko.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1041)
        at org.apache.pekko.actor.ActorSystemImpl._start(ActorSystem.scala:1040)
        at org.apache.pekko.actor.ActorSystemImpl.start(ActorSystem.scala:1064)
        at org.apache.pekko.actor.typed.ActorSystem$.createInternal(ActorSystem.scala:300)
        at org.apache.pekko.actor.typed.ActorSystem$.apply(ActorSystem.scala:208)
        at org.apache.pekko.actor.typed.ActorSystem$.create(ActorSystem.scala:245)
        at org.apache.pekko.actor.typed.ActorSystem.create(ActorSystem.scala)
        at com.example.ClusteringApp.main(ClusteringApp.java:13)
```

**Comment by pjfanning** [comment]
I'm not at my computer so I can't really debug this. Could you see if you can prevent the actor system shutdown? Temporarily add a long thread sleep if you have to. If this helps, we can find a prettier way to keep the actor system running.

**Comment by sam-byng** [comment]
That's fine. Just posting what i had. I am also seeing this in https://github.com/apache/incubator-pekko-samples/pull/38 for kubernetes cluster . However I think that the real issue may be test failure before shutdown is initiated. The timing issues in shutdown may be a separate issue with how we are handling test terminations

**Comment by sam-byng** [comment]
`Could you see if you can prevent the actor system shutdown? Temporarily add a long thread sleep if you have to. ` Will give this a go

**Comment by sam-byng** [comment]
The above issue is now fixed: 
1. logs were not going to the console appender
2. The path to the downing-provider-class was incorrect (string quoted + no `org.apache.pekko` path)

**Pull request merged**
