### PR TITLE
Publish more docs

### PR DESCRIPTION
**Pull request by mdedetrich**
Needed for pekko core documentation

### CODE REVIEW

**Comment by pjfanning** [comment]
I'm not an expert on the paradox stuff in this repo. But I think you need entries in https://github.com/apache/incubator-pekko-samples/blob/main/docs-gen/build.sbt and I don't think these are in there.

When in doubt, I've just been changing links in pekko docs to point at the GitHub READMEs instead. They have the same info.

**Comment by mdedetrich** [comment]
> I'm not an expert on the paradox stuff in this repo. But I think you need entries in https://github.com/apache/incubator-pekko-samples/blob/main/docs-gen/build.sbt and I don't think these are in there.

Done.

> When in doubt, I've just been changing links in pekko docs to point at the GitHub READMEs instead. They have the same info.
Ill try and get it done properly by tonight, but then I will give up and just point to README.md

**Comment by mdedetrich** [comment]
@pjfanning Okay so everything looks good and tests are passing

**Review by pjfanning — APPROVED** [review]
lgtm

**Pull request merged**
