### PR TITLE
Pekko #287: Migrate docker compose scala

### PR DESCRIPTION
**Pull request by sam-byng**
https://github.com/apache/incubator-pekko/issues/287

### CODE REVIEW

**Comment by sam-byng** [comment]
It seems to me that this might be showing the same issue as the java repo. However lacking logs here:

```
pekko-sample-cluster-docker-compose-scala$ ./scripts/test.sh
...
15:03:09,176 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [pekko] to false
15:03:09,176 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [console]. Did you define it below instead of above in the configuration file?
15:03:09,176 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
15:03:09,177 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
15:03:09,177 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [console]. Did you define it below instead of above in the configuration file?
15:03:09,177 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
15:03:09,177 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:03:09,177 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6f274f8 - Registering current configuration as safe fallback point

SLF4J: A number (4) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
```

**Comment by sam-byng** [comment]
Issue fixed by setting the appender namespace to 'console'

**Comment by pjfanning** [comment]
the tests are very flaky but a few runs seem to have reached this new sample's tests and failed both times - are these tests working ok?

**Comment by sam-byng** [comment]
Looks like a legit failure. Perhaps another test is using port 1600?

```
ERROR: for pekko-sample-cluster-docker-compose-scala_c1_1  Cannot start service c1: driver failed programming external connectivity on endpoint pekko-sample-cluster-docker-compose-scala_c1_1 (daf98c63bff2de243be74dcccb939c7f0472f3b4db6b5df9720c3e7cc8c46899): Bind for 0.0.0.0:1601 failed: port is already allocated
Host is already in use by another container
Creating pekko-sample-cluster-docker-compose-scala_seed_1 ... error

ERROR: for pekko-sample-cluster-docker-compose-scala_seed_1  Cannot start service seed: driver failed programming external connectivity on endpoint pekko-sample-cluster-docker-compose-scala_seed_1 (46334b60e00c0193b5804d268febf5c313e61beaa3f4e034a26d9ccb8a0a3eb3): Bind for 0.0.0.0:1600 failed: port is already allocated
```

**Comment by pjfanning** [comment]
I guess changing the ports is one way - but really shouldn't the tests be tidying up after themselves? we're not really trying to run the tests in parallel - so the java tests should complete and tear down their docker containers before we start the scala tests (or vice versa)

**Comment by sam-byng** [comment]
Ok - I've reverted that and added cleanup to the docker-compose and kubernetes-scala test.sh scripts.

**Review by pjfanning — APPROVED** [review]
lgtm

**Pull request merged**
